//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalTasbeehWithFriendsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class groupusertasbeehdeatiles
    {
        public int ID { get; set; }
        public Nullable<int> Group_Tasbeeh_Id { get; set; }
        public Nullable<int> Group_user_id { get; set; }
        public System.DateTime startdate { get; set; }
        public Nullable<System.DateTime> Enddate { get; set; }
        public Nullable<int> Assign_count { get; set; }
        public Nullable<int> Current_count { get; set; }
    }
}
