//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalTasbeehWithFriendsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quran_Tasbeeh
    {
        public int ID { get; set; }
        public string Sura_name { get; set; }
        public int Ayah_number_from { get; set; }
        public int Ayah_number_to { get; set; }
        public string Ayah_text { get; set; }
        public int Count { get; set; }
    }
}
