//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalTasbeehWithFriendsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int ID { get; set; }
        public int Tasbeeh_Id { get; set; }
        public int Sender_id { get; set; }
        public int Receiver_id { get; set; }
        public int Group_id { get; set; }
        public int Assigned_count { get; set; }
        public string Status { get; set; }
        public System.DateTime Send_at { get; set; }
        public Nullable<System.DateTime> Accept_at { get; set; }
        public Nullable<int> reminerid { get; set; }
    }
}
