//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalTasbeehWithFriendsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tasbeehlogs
    {
        public int ID { get; set; }
        public Nullable<int> Userid { get; set; }
        public Nullable<int> grouptasbeehid { get; set; }
        public Nullable<int> note { get; set; }
        public Nullable<System.DateTime> startat { get; set; }
        public Nullable<System.DateTime> leaveat { get; set; }
        public Nullable<int> Flag { get; set; }
    }
}
