//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalTasbeehWithFriendsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wazifa_Deatiles
    {
        public int id { get; set; }
        public int Wazifa_id { get; set; }
        public int wazifa_text_id { get; set; }
    }
}
